version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: rock_paper_scissors
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
